M48
; DRILL file {KiCad 9.0.0} date 2025-03-26T01:56:19+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-26T01:56:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0256
%
G90
G05
T1
X4.551Y-2.4366
T2
X4.551Y-2.2091
M30
